"""Translate strategies into ordinary Lean proof DAGs using kernel decide.

Python contributes no axioms. Descendants are shared by named Lean theorems.
"""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path
from check_narrow_odd import four, play


def board_term(key):
    return "(fourTuple " + " ".join("[" + ", ".join(".black" if p == "B" else ".white" for p in c) + "]"
                                    for c in key.split("|")) + ")"


def generate(policy, index, out, chunk_size, limit):
    cap, score, defender = (policy[k] for k in ("height", "win_rows", "defender"))
    enemy = "W" if defender == "B" else "B"
    p = ".black" if defender == "B" else ".white"
    states = sorted(policy["nodes"], key=lambda s: (-len(s.replace("|", "")), s))
    ids = {s: i for i, s in enumerate(states)}
    selected = states[:limit] if limit else states
    modules = []
    for start in range(0, len(selected), chunk_size):
        chunk = start // chunk_size
        name = f"P{index}_{chunk:04d}"
        previous = f"experiments.OddCertificates.{modules[-1]}" if modules else "experiments.FourColumnsOddFinite"
        lines = [f"import {previous}", "", "-- Generated by solver/generate_narrow_odd_lean.py",
                 "set_option maxRecDepth 100000", "set_option maxHeartbeats 0", "",
                 f"namespace Connect4.FourColumns.OddCertificate.P{index}", ""]
        for key in selected[start:start+chunk_size]:
            n = ids[key]
            b = tuple(key.split("|"))
            actions = policy["nodes"][key]
            reply = [actions.get(str(c+1)) or 1 for c in range(4)]
            lines.extend([f"def b{n} : Board 4 := {board_term(key)}",
                          f"theorem t{n} : ControlTree {cap} {score} {p} b{n} := by",
                          "  refine ControlTree.node (fourTuple " + " ".join(str(d-1) for d in reply) +
                          ") (by decide) (by decide) (by decide)",
                          "    (by decide) (by decide) (by decide) ?_",
                          "  intro c hc hf", "  fin_cases c"])
            for c in range(4):
                if len(b[c]) == cap:
                    lines.append(f"  · exact False.elim ((show ¬ Legal {cap} b{n} {c} from by decide) hc)")
                    continue
                child = play(b, c, enemy)
                if all(len(s) == cap for s in child):
                    lines.append("  · exact False.elim (hf (by decide))")
                    continue
                d = reply[c]-1
                after = play(child, d, defender)
                after_key = "|".join(after)
                if four(after, defender, score):
                    lines.append("  · exact ControlTree.won (by decide) (by decide)")
                elif all(len(s) == cap for s in after):
                    lines.append("  · exact ControlTree.full (by decide) (by decide)")
                else:
                    target = ids[after_key]
                    if target >= n:
                        raise ValueError("Certificate graph is not topologically ordered")
                    lines.extend([f"  · convert t{target} using 1",
                                  "    funext d",
                                  "    fin_cases d <;> rfl"])
            lines.append("")
        if len(selected) == len(states) and start+chunk_size >= len(states):
            root = ids[policy["root"]]
            lines.extend([f"theorem root : ControlTree {cap} {score} {p} {board_term(policy['root'])} := t{root}",
                          "#print axioms root", ""])
        lines.append(f"end Connect4.FourColumns.OddCertificate.P{index}")
        source = ("\n".join(lines) + "\n").replace("by decide", "by decide +kernel")
        (out / f"{name}.lean").write_text(source, encoding="utf-8", newline="\n")
        modules.append(name)
    return dict(policy=index, cap=cap, score=score, defender=defender,
                nodes_generated=len(selected), all_nodes=len(states),
                complete=len(selected) == len(states), modules=modules)


def generate_mirror(policy, index, parent, parent_module, out):
    name = f"P{index}_0000"
    p = ".black" if policy["defender"] == "B" else ".white"
    source = (f"import experiments.FourColumnsOddMirror\n"
              f"import experiments.OddCertificates.{parent_module}\n\n"
              "-- Generated by solver/generate_narrow_odd_lean.py\n"
              f"namespace Connect4.FourColumns.OddCertificate.P{index}\n\n"
              f"theorem root : ControlTree {policy['height']} {policy['win_rows']} {p} "
              f"{board_term(policy['root'])} := by\n"
              f"  convert ControlTree.mirror P{parent}.root using 1\n"
              "  funext c\n  fin_cases c <;> rfl\n\n"
              "#print axioms root\n\n"
              f"end Connect4.FourColumns.OddCertificate.P{index}\n")
    (out / (name + ".lean")).write_text(source, encoding="utf-8", newline="\n")
    return dict(policy=index, cap=policy["height"], score=policy["win_rows"],
                defender=policy["defender"], nodes_generated=0, all_nodes=len(policy["nodes"]),
                complete=True, mirror_of=parent, modules=[name])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--policies", nargs="+", type=int, default=list(range(14)))
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--chunk-size", type=int, default=1000)
    args = parser.parse_args()
    if args.chunk_size <= 0 or args.limit < 0 or any(not 0 <= i < 14 for i in args.policies):
        parser.error("Invalid policy, limit, or chunk size")
    certificate = json.loads(Path("reports/narrow_odd/strategies.json").read_text(encoding="utf-8"))
    if any(i >= 10 for i in args.policies):
        sys.path.insert(0, str(Path("experiments").resolve()))
        from narrow4_odd_lift import solve
        small = [solve(h, h, p, root) for h in (1, 3)
                 for p, root in (("B", ("B", "", "", "")), ("W", ("", "", "", "")))]
        Path("reports/narrow_odd/lean_small_strategies.json").write_text(
            json.dumps(small, sort_keys=True, separators=(",", ":")) + "\n",
            encoding="utf-8", newline="\n")
        certificate["policies"].extend(small)
    out = Path("experiments/OddCertificates")
    out.mkdir(parents=True, exist_ok=True)
    report = []
    for i in args.policies:
        if i in (7, 9) and not args.limit:
            parent = i-1
            chunks = (len(certificate["policies"][parent]["nodes"])-1)//args.chunk_size
            report.append(generate_mirror(certificate["policies"][i], i, parent,
                                          f"P{parent}_{chunks:04d}", out))
        else:
            report.append(generate(certificate["policies"][i], i, out, args.chunk_size, args.limit))
    Path("reports/narrow_odd/lean_generation.json").write_text(
        json.dumps(report, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(json.dumps(report), flush=True)


if __name__ == "__main__":
    main()
